### ISSUE TITLE
您好，请问您还保存着技能数据库的原始文件吗？

### ISSUE THREAD

**Issue by dzsqxhy** [taxeric/RocoGuideSql#1]
我指的是从洛克王国网页端直接拿下来的那个文件。因为您的数据库中没有技能对应特效文件的编号，原始文件中应该有的。我在复刻洛克王国，但是现在的技能数据库似乎已经过加密，所以想找您要一下源文件。我的邮箱：xi@jingtong.name

**Comment by taxeric** [comment]
您好，技能数据大部分是在4399精灵详情页爬下来的，另一部分从百科爬取，没有解析游戏。

**Comment by Asrtoxiaocan** [comment]
没用


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "taxeric/RocoGuideSql"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月7日(星期天) 凌晨1:41
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [taxeric/RocoGuideSql] 您好，请问您还保存着技能数据库的原始文件吗？ (Issue #1)





 
您好，技能数据大部分是在4399精灵详情页爬下来的，另一部分从百科爬取，没有解析游戏。

**Comment by taxeric** [comment]
@dzsqxhy 我已获取到原始的数据库, 是否需要发送到您的邮箱? (为最新数据库)
